package com.SchoolManagementSystem.Model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name="Feedback")
public class Feedback {

	/*
	 * ID is set as primary key and its value will be automatically generated by
	 * database
	 */
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private long ID;
	
	/* The firstName coulmn should not be null. */
	@Column(nullable=false)
	private String first_Name;
	
	/* The LastName coulmn should not be null. */
	@Column(nullable=false)
	private String last_Name;
	

	
	/* The Email coulmn should not be null and must be unique. */
	@Column(nullable=false,unique=true)
	private String email;
	
	/* The PhoneNo coulmn should not be null and must be unique. */
	@Column(nullable=false,unique=true,length=10)
	private String phone_no;
	
	/* The Description coulmn should not be null. */
	@Column(nullable=false)
	private String description;

	
	/* Default constructor with no fields */
	public Feedback() {
		
	}
	
	/* Constructor with all the fields */
	public Feedback(long iD, String first_Name, String last_Name, String email, String phone_no, String description) {
		super();
		ID = iD;
		this.first_Name = first_Name;
		this.last_Name = last_Name;
		this.email = email;
		this.phone_no = phone_no;
		this.description = description;
	}


	/* Getter & Setter method for First_Name */
	public String getFirst_Name() {
		return first_Name;
	}

	public void setFirst_Name(String first_Name) {
		this.first_Name = first_Name;
	}

	/* Getter & Setter method for Last_Name */
	public String getLast_Name() {
		return last_Name;
	}


	public void setLast_Name(String last_Name) {
		this.last_Name = last_Name;
	}

	/* Getter & Setter method for Email ID */
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	/* Getter & Setter method for Phone_no */
	public String getPhone_no() {
		return phone_no;
	}


	public void setPhone_no(String phone_no) {
		this.phone_no = phone_no;
	}

	/* Getter & Setter method for address */
	public String getDescription() {
		return description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}

	/* Getter & Setter method for FeedbackID */
	public long getID() {
		return ID;
	}

	public void setID(long iD) {
		ID = iD;
	}
	
	
	
	
}
